language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

install:
  - export COMPOSER_HOME=$(pwd)/.composer_home
  - export COMPOSER_CACHE=$(pwd)/.composer_cache
  - mkdir -p COMPOSER_HOME COMPOSER_CACHE
  - rm composer.lock
  - composer global require --no-progress --no-suggest --no-interaction --prefer-dist "phpunit/phpunit:8.*|^9.1" "behat/behat:3.*" friendsofphp/php-cs-fixer
  - composer install --no-dev --no-progress --no-suggest --no-interaction --prefer-dist --ignore-platform-reqs
  - composer dump -o -a --no-interaction

script:
  - ${COMPOSER_HOME}/vendor/bin/phpunit
  - ${COMPOSER_HOME}/vendor/bin/behat
  - ${COMPOSER_HOME}/vendor/bin/php-cs-fixer fix --dry-run --using-cache=no -v

cache:
  directories:
  - vendor
  - .composer_home
  - .composer_cache
